%YAML:1.0
---
image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [17908.65575,     0.     ,   481.34968,
             0.     , 15996.73682,   718.54338,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [-28.409467, 1282.423080, -0.271868, 0.636307, 0.000000]
rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [18082.16602,     0.     ,   526.97395,     0.     ,
             0.     , 16144.84277,   706.34979,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
